name: Build and Release 1.12.x

on:
  push:
    tags: 'v*'
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        id: set_up_jdk
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Get the version
        id: get_version
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
           return '${{ github.ref }}'.replace('refs/tags/v', '');
      - name: Setup mod dev workspace
        run: ./gradlew setupDevWorkspace
        env:
          VERSION:  ${{ steps.get_version.outputs.result }}
      - name: Build
        run: ./gradlew build
        env:
          VERSION:  ${{ steps.get_version.outputs.result }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.result }}
          release_name: TFCStorage MC1.12.2-${{ steps.get_version.outputs.result }}
          body: |
            [This was an automatic build]
            // todo: add changelog
          draft: false
          prerelease: false
      - name: Upload Main Jar
        id: upload_main_jar
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./build/libs/TFCStorage-MC1.12.2-${{ steps.get_version.outputs.result }}.jar
          asset_name: TFCStorage-MC1.12.2-${{ steps.get_version.outputs.result }}.jar
          asset_content_type: application/java-archive
      - name: Upload Deobf Jar
        id: upload_deobf_jar
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/TFCStorage-MC1.12.2-${{ steps.get_version.outputs.result }}-deobf.jar
          asset_name: TFCStorage-MC1.12.2-${{ steps.get_version.outputs.result }}-deobf.jar
          asset_content_type: application/java-archive
